---
aws_access_key: "{{ vaulted_aws_access_key }}"
aws_secret_key: "{{ vaulted_aws_secret_key }}"
ec2_keypair: "{{ vaulted_ec2_keypair }}"
ec2_url: https://ec2.amazonaws.com
ec2_x86_instance_type: t2.micro
ec2_arm_instance_type: a1.medium
ec2_region: eu-west-1
ec2_group: default
ec2_internet_gateway: default-igw
ec2_instance_count: 1
ec2_instance_tag: 
  name: demo
rhel7:
  arm: 
    image: ami-0b5171a7b859ff1b4
    instance: a1.medium
  x86: 
    image: ami-0e12cbde3e77cbb98
    instance: t2.micro
rhel8:
  x86: 
    image: ami-08f4717d06813bf00
    instance: t2.micro

ec2_image: "{{ rhel8.x86.image }}"
ec2_instance_type: "{{ rhel8.x86.instance  }}"
