# plays/create-ec2-instances.yml

- name: create sandbox instance
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ec2_instance_count: 2
    ec2_instance_tag: 
      name: sandbox
    ec2_instance_type: a1.medium
    ec2_image: ami-0b5171a7b859ff1b4

  tasks:
    - name: gather facts from the ec2 virtual private cloud
      ec2_vpc_net_facts:
        filters:
          isDefault: "true"
        region: "{{ ec2_region }}"
      register: ec2_vpc_net_facts

    - name: gather ec2 subnet facts
      ec2_vpc_subnet_facts:
        filters:
          defaultForAz: "true"
        region: "{{ ec2_region }}"
      register: ec2_vpc_subnet_facts
    
    - name: provision ec2 sandbox instance
      ec2:
        assign_public_ip: yes
        count_tag: "{{ ec2_instance_tag }}"
        exact_count: "{{ ec2_instance_count }}"
        groups: "{{ ec2_group }}"
        key_name: "{{ ec2_keypair }}"
        image: "{{ ec2_image }}"
        instance_tags: "{{ ec2_instance_tag }}"
        instance_type: "{{ ec2_instance_type }}"
        region: "{{ ec2_region }}"
        volumes:
          - device_name: /dev/sda1
            delete_on_termination: true
            volume_type: gp2
            volume_size: 40
        vpc_subnet_id: "{{ ec2_vpc_subnet_facts.subnets[0].subnet_id }}"
        wait: true
      register: ec2

    - name: sandbox hostname
      debug:
        var: item.dns_name
      loop: "{{ ec2.tagged_instances }}"

# vim:sw=2:ts=2:et

