# plays/destroy-ec2-instances.yml
#
# Destroy the EC2 instance

- name: destroy ec2 instances
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: destroy ec2 instances
      ec2:
        count_tag: "{{ ec2_instance_tag }}"
        instance_ids: "{{ hostvars[inventory_hostname].ec2_id }}"
        region: "{{ ec2_region }}"
        state: absent
      register: ec2

# vim:sw=2:ts=2:et


